# .github/workflows/release-please.yml
name: release-please
on:
  push:
    branches:
      - main
      - 'hotfix/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
